/**
 * ============================================================================
 * SPJ PACKAGE GENERATOR - Complete SPJ Bundle Generator
 * ============================================================================
 *
 * Service untuk generate paket SPJ (Surat Pertanggungjawaban) lengkap yang
 * menggabungkan semua dokumen pendukung dalam satu bundle.
 *
 * Features:
 * - Generate complete SPJ package dengan semua dokumen
 * - Auto-generate cover dan lembar pengesahan
 * - Auto-generate daftar isi (table of contents)
 * - Auto-generate kronologi administratif (timeline)
 * - Bundle multiple document types (SPR, SPPR, BA, PPHP, BAST, Perdin, etc.)
 * - Export to ZIP archive atau single PDF
 * - FASE 4.5 fiscal year integration
 * - Compliance-ready untuk audit BPK
 *
 * Package Structure:
 * 1. Cover (SPJPackageCover.template.html)
 * 2. Lembar Pengesahan (SPJPackagePengesahan.template.html)
 * 3. Daftar Isi (auto-generated)
 * 4. Kronologi Administratif (auto-generated)
 * 5. Supporting Documents (SPR, SPPR, BA, PPHP, BAST, Perdin, etc.)
 *
 * @author Admin PPK Development Team
 * @version 1.0.0
 */

import * as fs from 'fs/promises'
import * as path from 'path'
import { fileURLToPath } from 'url'
import Handlebars from 'handlebars'
import fiscalYearContext from '../fiscal/FiscalYearContext.js'
import sprGenerator from './SPRGenerator.js'
import kuitansiPerdinGenerator from './KuitansiPerdinGenerator.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

/**
 * Document type priorities for ordering in package
 */
const DOCUMENT_ORDER = {
  'SPJ_COVER': 1,
  'SPJ_PENGESAHAN': 2,
  'DAFTAR_ISI': 3,
  'KRONOLOGI': 4,
  'SPR': 10,
  'SPPR': 11,
  'BA_PEMBAYARAN': 20,
  'PPHP': 21,
  'BAST': 22,
  'KUITANSI_UM_PERDIN': 30,
  'RINCIAN_BIAYA_PERDIN': 31,
  'KUITANSI_RAMPUNG_PERDIN': 32,
  'TANDA_TERIMA_UPTUP': 40,
  'RPD': 50
}

/**
 * SPJ Package Generator Class
 */
export class SPJPackageGenerator {
  constructor() {
    this.templates = {
      cover: path.resolve(__dirname, '../../templates/documents/SPJPackageCover.template.html'),
      pengesahan: path.resolve(__dirname, '../../templates/documents/SPJPackagePengesahan.template.html')
    }
    this.compiledTemplates = {}

    // Register Handlebars helpers
    this._registerHelpers()
  }

  /**
   * Register Handlebars helpers
   * @private
   */
  _registerHelpers() {
    Handlebars.registerHelper('formatCurrency', (amount) => {
      return this._formatCurrency(amount)
    })

    Handlebars.registerHelper('increment', (index) => {
      return index + 1
    })

    Handlebars.registerHelper('romanNumeral', (num) => {
      return this._toRoman(num)
    })
  }

  /**
   * Load templates
   * @returns {Promise<void>}
   */
  async loadTemplates() {
    if (Object.keys(this.compiledTemplates).length === 2) return

    try {
      for (const [key, templatePath] of Object.entries(this.templates)) {
        const templateContent = await fs.readFile(templatePath, 'utf-8')
        this.compiledTemplates[key] = Handlebars.compile(templateContent)
      }
      console.log('[SPJPackageGenerator] Templates loaded successfully')
    } catch (error) {
      console.error('[SPJPackageGenerator] Failed to load templates:', error)
      throw new Error(`Failed to load SPJ Package templates: ${error.message}`)
    }
  }

  /**
   * Generate complete SPJ package
   *
   * @param {Object} masterData - Master data for SPJ
   * @param {Array<Object>} documents - Array of supporting documents
   * @param {Object} options - Generation options
   * @returns {Promise<Object>} Complete SPJ package
   *
   * Options:
   * - includeCover: boolean (default: true)
   * - includePengesahan: boolean (default: true)
   * - includeDaftarIsi: boolean (default: true)
   * - includeKronologi: boolean (default: true)
   * - autoGenerateDocuments: boolean (default: false) - Auto-generate missing docs
   * - format: 'bundle' | 'zip' | 'pdf' (default: 'bundle')
   */
  async generate(masterData, documents = [], options = {}) {
    await this.loadTemplates()

    const {
      includeCover = true,
      includePengesahan = true,
      includeDaftarIsi = true,
      includeKronologi = true,
      autoGenerateDocuments = false,
      format = 'bundle'
    } = options

    console.log('[SPJPackageGenerator] Generating SPJ Package:', masterData.namaKegiatan || masterData.nama_kegiatan)

    // Get fiscal year context
    const tahunAnggaran = options.tahunAnggaran || fiscalYearContext.getActiveYear()
    const isReconstruction = options.isReconstruction || fiscalYearContext.isReconstructionMode()

    // Calculate total nilai
    const nilaiTotal = this._calculateTotalNilai(documents, masterData)

    // Prepare package data
    const packageData = {
      tahun_anggaran: tahunAnggaran,
      nama_kegiatan: masterData.namaKegiatan || masterData.nama_kegiatan || '',
      nama_output: masterData.namaOutput || masterData.nama_output || '',
      kode_kegiatan: masterData.kodeKegiatan || masterData.kode_kegiatan || '',
      nama_satker: masterData.satkerNama || masterData.nama_satker || '',
      kode_satker: masterData.satkerKode || masterData.kode_satker || '',
      sumber_dana: masterData.sumberDana || masterData.sumber_dana || 'APBN',
      jenis_pembayaran: masterData.jenisPembayaran || masterData.jenis_pembayaran || 'UP',
      nilai_total: this._formatCurrency(nilaiTotal),
      nilai_terbilang: this._numberToWords(nilaiTotal),

      // Pejabat
      nama_ppk: masterData.ppkNama || masterData.nama_ppk || '',
      nip_ppk: masterData.ppkNip || masterData.nip_ppk || '',
      nama_kpa: masterData.kpaNama || masterData.nama_kpa || '',
      nip_kpa: masterData.kpaNip || masterData.nip_kpa || '',
      nama_bendahara: masterData.bendaharaNama || masterData.nama_bendahara || '',
      nip_bendahara: masterData.bendaharaNip || masterData.nip_bendahara || '',

      // Kop
      logo_satker: masterData.logo_satker || '/assets/logo-kkp.png',
      nama_unit_eselon1: masterData.nama_unit_eselon1 || 'DIREKTORAT JENDERAL ...',
      nama_satuan_kerja: masterData.nama_satuan_kerja || masterData.satkerNama || '',
      alamat_satker: masterData.alamat_satker || '',
      telepon: masterData.telepon || '',
      email: masterData.email || '',

      // Location & Date
      kota: masterData.kota || masterData.kotaSatker || 'Jakarta',
      tanggal: this._formatTanggalSurat(masterData.tanggalPengesahan || new Date()),

      // FASE 4.5
      tahunAnggaran,
      isReconstruction,
      reconstructionDate: isReconstruction ? this._formatTanggalSurat(new Date()) : null
    }

    // Generate package components
    const packageDocuments = []

    // 1. Cover
    if (includeCover) {
      const cover = {
        type: 'SPJ_COVER',
        title: 'Cover Paket SPJ',
        html: this.compiledTemplates.cover(packageData),
        data: packageData,
        order: DOCUMENT_ORDER.SPJ_COVER
      }
      packageDocuments.push(cover)
    }

    // 2. Lembar Pengesahan
    if (includePengesahan) {
      const pengesahan = {
        type: 'SPJ_PENGESAHAN',
        title: 'Lembar Pengesahan',
        html: this.compiledTemplates.pengesahan(packageData),
        data: packageData,
        order: DOCUMENT_ORDER.SPJ_PENGESAHAN
      }
      packageDocuments.push(pengesahan)
    }

    // 3. Daftar Isi
    if (includeDaftarIsi) {
      const daftarIsi = await this._generateDaftarIsi(documents, packageData)
      packageDocuments.push(daftarIsi)
    }

    // 4. Kronologi
    if (includeKronologi) {
      const kronologi = await this._generateKronologi(documents, masterData, packageData)
      packageDocuments.push(kronologi)
    }

    // 5. Add supporting documents
    packageDocuments.push(...documents)

    // Sort by order
    packageDocuments.sort((a, b) => {
      const orderA = a.order || DOCUMENT_ORDER[a.type] || 999
      const orderB = b.order || DOCUMENT_ORDER[b.type] || 999
      return orderA - orderB
    })

    // Create package object
    const spjPackage = {
      type: 'SPJ_PACKAGE',
      title: `Paket SPJ - ${packageData.nama_kegiatan}`,
      documents: packageDocuments,
      metadata: {
        generatedAt: new Date().toISOString(),
        tahunAnggaran,
        isReconstruction,
        totalDocuments: packageDocuments.length,
        totalNilai: nilaiTotal,
        masterDataId: masterData.masterId || masterData.id
      }
    }

    console.log(`[SPJPackageGenerator] Package generated: ${packageDocuments.length} documents, Total: Rp ${this._formatCurrency(nilaiTotal)}`)

    return spjPackage
  }

  /**
   * Generate Daftar Isi (Table of Contents)
   * @private
   */
  async _generateDaftarIsi(documents, packageData) {
    const items = documents.map((doc, index) => ({
      nomor: index + 1,
      romanNumeral: this._toRoman(index + 1),
      namaFile: doc.title || doc.type,
      halaman: index + 5 // Start after cover, pengesahan, daftar isi, kronologi
    }))

    const html = `
<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Daftar Isi - Paket SPJ</title>
  <style>
    @page { size: A4; margin: 2.5cm; }
    body { font-family: "Times New Roman", serif; font-size: 12pt; margin: 2.5cm; }

    .kop { text-align: center; margin-bottom: 20px; }
    .kop-logo { height: 80px; margin-bottom: 10px; }
    .kop-text { font-weight: bold; line-height: 1.3; }
    .kop-title { font-size: 14pt; text-transform: uppercase; }
    .kop-line { border: none; border-bottom: 3px solid #000; margin: 10px 0 20px 0; }

    .document-title { text-align: center; margin: 30px 0; }
    .document-title h1 { font-size: 14pt; font-weight: bold; text-decoration: underline; margin: 0; }

    .toc-table { width: 100%; border-collapse: collapse; margin-top: 30px; }
    .toc-table th, .toc-table td { border: 1px solid #000; padding: 10px; }
    .toc-table th { background-color: #e0e0e0; font-weight: bold; text-align: center; }
    .toc-table .col-no { width: 60px; text-align: center; }
    .toc-table .col-file { text-align: left; }
    .toc-table .col-page { width: 80px; text-align: center; }
  </style>
</head>
<body>

<div class="kop">
  ${packageData.logo_satker ? `<img src="${packageData.logo_satker}" class="kop-logo">` : ''}
  <div class="kop-text">
    <div class="kop-title">KEMENTERIAN KELAUTAN DAN PERIKANAN</div>
    <div>${packageData.nama_unit_eselon1}</div>
    <div>${packageData.nama_satuan_kerja}</div>
  </div>
  <hr class="kop-line">
</div>

<div class="document-title">
  <h1>DAFTAR ISI</h1>
  <div style="margin-top: 10px;">PAKET SPJ TAHUN ANGGARAN ${packageData.tahun_anggaran}</div>
</div>

<table class="toc-table">
  <thead>
    <tr>
      <th class="col-no">No</th>
      <th class="col-file">Nama Dokumen</th>
      <th class="col-page">Halaman</th>
    </tr>
  </thead>
  <tbody>
    ${items.map(item => `
    <tr>
      <td class="col-no">${item.romanNumeral}</td>
      <td class="col-file">${item.namaFile}</td>
      <td class="col-page">${item.halaman}</td>
    </tr>
    `).join('')}
  </tbody>
</table>

</body>
</html>
    `

    return {
      type: 'DAFTAR_ISI',
      title: 'Daftar Isi',
      html: html.trim(),
      data: { items },
      order: DOCUMENT_ORDER.DAFTAR_ISI
    }
  }

  /**
   * Generate Kronologi Administratif (Administrative Timeline)
   * @private
   */
  async _generateKronologi(documents, masterData, packageData) {
    // Extract timeline events from documents
    const events = []

    // Add master event (kegiatan start)
    if (masterData.tanggalMulai) {
      events.push({
        tanggal: this._formatTanggalSurat(masterData.tanggalMulai),
        uraian: `Dimulainya kegiatan: ${packageData.nama_kegiatan}`,
        keterangan: 'Tahap pelaksanaan kegiatan'
      })
    }

    // Extract events from documents
    for (const doc of documents) {
      if (doc.data?.tanggal || doc.metadata?.generatedAt) {
        const tanggal = doc.data?.tanggal || this._formatTanggalSurat(new Date(doc.metadata.generatedAt))
        events.push({
          tanggal,
          uraian: `Penerbitan ${doc.title}`,
          keterangan: `Dokumen: ${doc.type}`
        })
      }
    }

    // Sort by date
    events.sort((a, b) => new Date(a.tanggal) - new Date(b.tanggal))

    const html = `
<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Kronologi Administratif - Paket SPJ</title>
  <style>
    @page { size: A4; margin: 2.5cm; }
    body { font-family: "Times New Roman", serif; font-size: 12pt; margin: 2.5cm; }

    .kop { text-align: center; margin-bottom: 20px; }
    .kop-logo { height: 80px; margin-bottom: 10px; }
    .kop-text { font-weight: bold; line-height: 1.3; }
    .kop-title { font-size: 14pt; text-transform: uppercase; }
    .kop-line { border: none; border-bottom: 3px solid #000; margin: 10px 0 20px 0; }

    .document-title { text-align: center; margin: 30px 0; }
    .document-title h1 { font-size: 14pt; font-weight: bold; text-decoration: underline; margin: 0; }

    .kronologi-table { width: 100%; border-collapse: collapse; margin-top: 30px; }
    .kronologi-table th, .kronologi-table td { border: 1px solid #000; padding: 10px; }
    .kronologi-table th { background-color: #e0e0e0; font-weight: bold; text-align: center; }
    .kronologi-table .col-no { width: 50px; text-align: center; }
    .kronologi-table .col-tanggal { width: 120px; text-align: center; }
    .kronologi-table .col-uraian { text-align: left; }
    .kronologi-table .col-ket { width: 200px; text-align: left; }
  </style>
</head>
<body>

<div class="kop">
  ${packageData.logo_satker ? `<img src="${packageData.logo_satker}" class="kop-logo">` : ''}
  <div class="kop-text">
    <div class="kop-title">KEMENTERIAN KELAUTAN DAN PERIKANAN</div>
    <div>${packageData.nama_unit_eselon1}</div>
    <div>${packageData.nama_satuan_kerja}</div>
  </div>
  <hr class="kop-line">
</div>

<div class="document-title">
  <h1>KRONOLOGI ADMINISTRATIF</h1>
  <div style="margin-top: 10px;">PAKET SPJ TAHUN ANGGARAN ${packageData.tahun_anggaran}</div>
  <div style="margin-top: 5px; font-weight: bold;">${packageData.nama_kegiatan}</div>
</div>

<table class="kronologi-table">
  <thead>
    <tr>
      <th class="col-no">No</th>
      <th class="col-tanggal">Tanggal</th>
      <th class="col-uraian">Uraian Kegiatan</th>
      <th class="col-ket">Keterangan</th>
    </tr>
  </thead>
  <tbody>
    ${events.map((event, index) => `
    <tr>
      <td class="col-no">${index + 1}</td>
      <td class="col-tanggal">${event.tanggal}</td>
      <td class="col-uraian">${event.uraian}</td>
      <td class="col-ket">${event.keterangan}</td>
    </tr>
    `).join('')}
  </tbody>
</table>

<div style="margin-top: 30px; text-align: center; font-style: italic; font-size: 10pt;">
  Kronologi ini disusun berdasarkan urutan waktu pelaksanaan kegiatan dan penerbitan dokumen administratif
</div>

</body>
</html>
    `

    return {
      type: 'KRONOLOGI',
      title: 'Kronologi Administratif',
      html: html.trim(),
      data: { events },
      order: DOCUMENT_ORDER.KRONOLOGI
    }
  }

  /**
   * Calculate total nilai from all documents
   * @private
   */
  _calculateTotalNilai(documents, masterData) {
    // If masterData has explicit total, use it
    if (masterData.nilaiTotal || masterData.nilai_total) {
      return masterData.nilaiTotal || masterData.nilai_total
    }

    // Otherwise sum from documents
    let total = 0

    for (const doc of documents) {
      // Try to extract nilai from various fields
      const nilai = doc.data?.jumlah_angka ||
        doc.data?.nilai_dibayar ||
        doc.data?.nilai_kontrak ||
        doc.data?.total_biaya_riil ||
        doc.data?.grand_total ||
        0

      // Clean currency formatting if present
      const cleanNilai = typeof nilai === 'string'
        ? parseInt(nilai.replace(/\./g, ''))
        : nilai

      total += cleanNilai
    }

    return total
  }

  /**
   * Save package to directory or ZIP
   *
   * @param {Object} spjPackage - SPJ package object
   * @param {string} outputPath - Output path
   * @param {Object} options - Save options
   * @returns {Promise<void>}
   */
  async save(spjPackage, outputPath, options = {}) {
    const { format = 'directory' } = options

    try {
      if (format === 'directory') {
        // Create directory
        await fs.mkdir(outputPath, { recursive: true })

        // Save each document
        for (let i = 0; i < spjPackage.documents.length; i++) {
          const doc = spjPackage.documents[i]
          const filename = `${String(i + 1).padStart(2, '0')}-${doc.type}.html`
          const filepath = path.join(outputPath, filename)
          await fs.writeFile(filepath, doc.html, 'utf-8')
        }

        // Save metadata
        const metadataPath = path.join(outputPath, 'metadata.json')
        await fs.writeFile(metadataPath, JSON.stringify(spjPackage.metadata, null, 2), 'utf-8')

        console.log(`[SPJPackageGenerator] Package saved to directory: ${outputPath}`)
      } else if (format === 'zip') {
        // TODO: Implement ZIP packaging using archiver or jszip
        console.log('[SPJPackageGenerator] ZIP format not yet implemented')
      }
    } catch (error) {
      console.error(`[SPJPackageGenerator] Failed to save package:`, error)
      throw error
    }
  }

  // ============================================================================
  // HELPER METHODS
  // ============================================================================

  _formatCurrency(amount) {
    return new Intl.NumberFormat('id-ID', {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(amount)
  }

  _numberToWords(num) {
    if (num === 0) return 'Nol Rupiah'

    const units = ['', 'Satu', 'Dua', 'Tiga', 'Empat', 'Lima', 'Enam', 'Tujuh', 'Delapan', 'Sembilan']
    const teens = [
      'Sepuluh', 'Sebelas', 'Dua Belas', 'Tiga Belas', 'Empat Belas',
      'Lima Belas', 'Enam Belas', 'Tujuh Belas', 'Delapan Belas', 'Sembilan Belas'
    ]

    const convert = (n) => {
      if (n === 0) return ''
      if (n < 10) return units[n]
      if (n >= 10 && n < 20) return teens[n - 10]
      if (n >= 20 && n < 100) {
        return units[Math.floor(n / 10)] + ' Puluh ' + units[n % 10]
      }
      if (n >= 100 && n < 200) {
        return 'Seratus ' + convert(n - 100)
      }
      if (n >= 200 && n < 1000) {
        return units[Math.floor(n / 100)] + ' Ratus ' + convert(n % 100)
      }
      if (n >= 1000 && n < 2000) {
        return 'Seribu ' + convert(n - 1000)
      }
      if (n >= 2000 && n < 1000000) {
        return convert(Math.floor(n / 1000)) + ' Ribu ' + convert(n % 1000)
      }
      if (n >= 1000000 && n < 1000000000) {
        return convert(Math.floor(n / 1000000)) + ' Juta ' + convert(n % 1000000)
      }
      if (n >= 1000000000 && n < 1000000000000) {
        return convert(Math.floor(n / 1000000000)) + ' Miliar ' + convert(n % 1000000000)
      }
      return n.toString()
    }

    return convert(num).trim() + ' Rupiah'
  }

  _formatTanggalSurat(date) {
    const d = typeof date === 'string' ? new Date(date) : date

    const bulan = [
      'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
      'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'
    ]

    return `${d.getDate()} ${bulan[d.getMonth()]} ${d.getFullYear()}`
  }

  _toRoman(num) {
    const lookup = {
      M: 1000, CM: 900, D: 500, CD: 400,
      C: 100, XC: 90, L: 50, XL: 40,
      X: 10, IX: 9, V: 5, IV: 4, I: 1
    }

    let roman = ''
    for (let i in lookup) {
      while (num >= lookup[i]) {
        roman += i
        num -= lookup[i]
      }
    }
    return roman
  }
}

// Export singleton instance
const spjPackageGenerator = new SPJPackageGenerator()
export default spjPackageGenerator
